# -*- coding: utf-8 -*-
"""RPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikBpOBTCQU4jF3bSoIDvaCqoXCpagXZb
"""

import random

# Definir constantes para los movimientos
ROCA = "R"
PAPEL = "P"
TIJERAS = "S"

def player(prev_play, opponent_history=[]):
    if prev_play:
        opponent_history.append(prev_play)

    # Si es el primer turno, juega aleatoriamente
    if len(opponent_history) == 0:
        return random.choice([ROCA, PAPEL, TIJERAS])

    # Estrategia basada en el último movimiento del oponente
    last_move = opponent_history[-1]

    # Juega lo que vence al último movimiento del oponente
    if last_move == ROCA:
        return PAPEL  # Papel vence a Roca
    elif last_move == PAPEL:
        return TIJERAS  # Tijeras vence a Papel
    else:
        return ROCA  # Roca vence a Tijeras